dogcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('dogs/', views.dogs_index, name='index'),
    path('dogs/<int:dog_id>/', views.dogs_detail, name="detail"),
    path('dogs/create/', views.DogCreate.as_view(), name='dogs_create'),
    path('dogs/<int:pk>/update/', views.DogUpdate.as_view(), name='dogs_update'),
    path('dogs/<int:pk>/delete/', views.DogDelete.as_view(), name="dogs_delete"),
    path('dogs/<int:dog_id>/add_feeding/',
         views.add_feeding, name='add_feeding'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)

# Create your models here.
class Dog(models.Model):
  name = models.CharField(max_length=100)
  breed = models.CharField(max_length=100)
  description = models.TextField(max_length=250)
  age = models.IntegerField()

  def __str__(self):
      return self.name

    # This is another way of redirecting after creating a dog
  def get_absolute_url(self):
      return reverse('detail', kwargs={'dog_id': self.id})

  class Meta:
      ordering = ['id']

class Feeding(models.Model):
    date = models.DateField('Feeding date')
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0]
    )

    # This creates a Foreign Key (FK) and deletes all the information related to a deleted cat so there is no data related to something that doesn't exist anymore (no orphan data)
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"

    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponse
from .models import Dog
from .forms import FeedingForm

# Create your views here.
def home(request):
    return HttpResponse('<h1>Hewwoooooooooooo</h1>')

def about(request):
    return render(request, 'about.html')

def dogs_index(request):
    dogs = Dog.objects.all()
    return render(request, 'dogs/index.html', { 'dogs': dogs })

def dogs_detail(request, dog_id):
    dog = Dog.objects.get(id=dog_id)
    feeding_form = FeedingForm()
    return render(request, 'dogs/detail.html', { 'dog': dog, 'feeding_form': feeding_form })

def add_feeding(request, dog_id):
  # create a ModelForm instance using the data in request.POST
  form = FeedingForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the database until it
    # has the dog_id assigned
    new_feeding = form.save(commit=False)
    new_feeding.dog_id = dog_id
    new_feeding.save()
  return redirect('detail', dog_id=dog_id)

class DogCreate(CreateView):
  model = Dog
  fields = '__all__'
  # This is one way of redirecting after creating a dog
  # success_url = "/dogs/"

class DogUpdate(UpdateView):
  model = Dog
  fields = ['breed', 'description', 'age']

class DogDelete(DeleteView):
  model = Dog
  success_url = '/dogs/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Dog Collector</h1>
<hr />
<p>Hire the Dog Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dog Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Dog Collector</a></li>
                </ul>
                <ul class="right">
                    <li><a href="{% url 'about' %}">About</a></li>
                    <li><a href="{% url 'dogs_create' %}">Add a doggo</a></li>
                    <li><a href="{% url 'index' %}">View All Doggos</a></li>
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
  	<footer class="page-footer">
       <div class="right">All Rights Reserved, &copy; 2019 Dog Collector &nbsp;</div>
    </footer>
</body>
</html>

main_app/templates/dogs/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Dog Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ dog.name }}</span>
        <p>Breed: {{ dog.breed }}</p>
        <p>Description: {{ dog.description }}</p>
        {% if dog.age > 0 %}
          <p>Age: {{ dog.age }}</p>
        {% else %}
          <p>Age: Pupperino</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'dogs_update' dog.id %}">Edit</a>
        <a href="{% url 'dogs_delete' dog.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_feeding' dog.id %}" method="POST">
      {% csrf_token %}
      {{ feeding_form.as_p }}
      <input type="submit" value="Add Feeding" class="btn">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Meal</th></tr>
      </thead>
      <tbody>
        {% for feeding in dog.feeding_set.all %}
          <tr>
            <td>{{feeding.date}}</td>
            <td>{{feeding.get_meal_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<script>
  var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
  var selectEl = document.getElementById('id_meal');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/dogs/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Dog List</h1>

{% for dog in dogs %}
  <div class="card">
    <a href="{% url 'detail' dog.id %}">
    <div class="card-content">
      <span class="card-title">{{ dog.name }}</span>
      <p>Breed: {{ dog.breed }}</p>
      <p>Description: {{ dog.description }}</p>
      {% if dog.age > 0 %}
        <p>Age: {{ dog.age }}</p>
      {% else %}
        <p>Age: Pupperino</p>
      {% endif %}
    </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/main_app/dog_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Dog</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' dog.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/dog_form.html
{% extends 'base.html' %}

{% block content %}

<!-- Leaving the action empty makes the form post to the same url used to display, this is what Django is expecting -->
<form action="" method="POST">
    {% if object %}
        <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
    {% else %}
        <h1>Add Dog</h1>
     {% endif %}
    <!-- Django requires the following security purposes -->
    {% csrf_token %}
    <table>
        <!-- Render the inputs inside of <tr>s and <td>s -->
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
</form>

{% endblock%}